directories:
  output: build-output-1.4.21
  buildResources: build
artifactName: Nihul Beit Cnecet Setup ${version}.exe
compression: store
extraResources:
  - from: dist
    to: dist
appId: com.synagogue.management
productName: Nihul Beit Cnecet
asar: false
files:
  - filter:
      - dist/**/*
      - public/**/*
      - index.js
      - electron.cjs
      - package.json
      - data/**/*
      - '!**/node_modules/antd/**'
      - '!**/node_modules/@ant-design/**'
      - '!**/node_modules/react/**'
      - '!**/node_modules/react-dom/**'
      - '!**/node_modules/lucide-react/**'
win:
  target: nsis
  icon: build/prague_synagogue_icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  runAfterFinish: true
  useZip: true
electronVersion: 40.3.0
